// models/Resume.js
import mongoose from 'mongoose';

const resumeSchema = new mongoose.Schema({
  
  title: { type: String, required: true },
  resumeId: { type: String, required: true, unique: true }, // Generated by frontend
  userEmail: { type: String, required: true }, // From Clerk
  userName: { type: String, required: true }, // From Clerk
  personalDetails: {
    firstName: String,
    lastName: String,
    jobTitle: String,
    address: String,
    phone: String,
    email: String,
  },
  education: [
    {
      universityName: String,
      degree: String,
      major: String,
      startDate: String,
      endDate: String,
      description: String,
    },
  ],
  experience: [
    {
      title: String,
      companyName: String,
      city: String,
      state: String,
      startDate: String,
      endDate: String,
      workSummary: String,
    },
  ],
  skills: [
    {
      name: String,
      rating: Number,
    },
  ],
  summery: { type: String, required: true },
  themeColor: String,
  createdAt: { type: Date, default: Date.now },
});

const Resume = mongoose.model('Resume', resumeSchema);

export default Resume;